### ISSUE TITLE
dumps url is broken

### ISSUE THREAD

**Issue by kylemcdonald** [snoack/cocktail-search#11]
is there still a dump available? the `http://cocktails.djacap.net/dumps/` url appears to have migrated.

i tried to manually navigate to where the .json might be, as well:

http://cocktails.etrigg.com/dumps/crawler/wikipedia.json

and

http://cocktails.djacap.net/dumps/crawler/wikipedia.json

**Comment by snoack** [comment]
The current URL is http://cocktails.etrigg.com/dumps/wikipedia.json
