### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by tristaneuan** [snoack/cocktail-search#12]
I'm getting a 403 error when I try to access http://cocktails.etrigg.com/ or `wget` the recipe dumps.

**Comment by snoack** [comment]
A friend has been so kind to host it on his server. And it seems that it's currently down.

@patrick-jay Any chance to get it up again under some domain?

**Comment by patrick-jay** [comment]
strange, should be ok - i'm lookin' into it...

**Comment by patrick-jay** [comment]
works now!

cheers

p

**Comment by tristaneuan** [comment]
Awesome, thank you both! Definitely going to be making use of this over the weekend. :cocktail:

**Comment by snoack** [comment]
Thanks a lot, @patrick-jay!

Enjoy, @tristaneuan!
